import React, { useState } from 'react'
import Select from 'react-select'
import styled from 'styled-components';
import Popover from '@mui/material/Popover';

const Wrapper = styled.div`
    width: 100%;
    height: 100vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
`

const HeadlineComparisonContainer = styled.div`
    display: flex;
    flex-direction: row;
    align-items: center;
    margin-top: 10px;
    position: relative;

    @media only screen and (max-width: 600px) {
        flex-direction: column;
    }
`

const HeadlineContainer = styled.div`
    border-radius: 10px;
    background-color: #fff1e6;
    margin: 5px;
    padding: 20px;
    text-align: center;
    max-width: 215px;
    transition: background-color 0.2s;
    cursor: pointer;

    :hover {
        background-color: #EEDBCD;
    }
`

const HeadlineTitle = styled.h5`
    margin: 0;
    padding: 0;
    margin-bottom: 5px;
`

const ModalTitle = styled.h3`
    margin: 0;
    padding: 0;
    margin-bottom: 5px;
`

const Description = styled.p`
    margin: 0;
    margin-bottom: 20px;
    font-weight: bold;
    max-width: 600px;
    text-align: center;
`

const Modal = styled.div`
    height: 300px;
    width: 300px;
    display: flex;
    flex-direction: column;
    padding: 10px;
    align-items: center;
`

const SentimentBubble = styled.div`
    height: ${props => Math.abs(props.score) <= 0 ? "25" : Math.abs(props.score) * 200}px;
    width: ${props => Math.abs(props.score) <= 0 ? "25" : Math.abs(props.score) * 200}px;
    min-height: 50px;
    min-width: 50px;
    border-radius: ${props => (Math.abs(props.score) * 200) / 2 < 25 ? "25" : Math.abs(props.score) * 200 / 2}px;
    background-color: ${props => props.score <= 0 ? "#FA6262" : " #a5a58d"};
    color: black;
    font-size: 14px;
    font-weight: bold;
    display: flex;
    justify-content: center;
    align-items: center;
`

const SemanticSimilarity = styled.p`
    background-color: #f0efeb;
    border-radius: 10px;
    padding: 10px;
    margin: 10px;
    text-align: center;
`

// Articles hardcoded because they don't change
const options = [
    {
        label: "Upworthy Articles",
        options: [
            {
                label: "Rape Article from Upworthy",
                value: "RapeArticle"
            },
            {
                label: "Sexism Against Men from Upworthy",
                value: "SexismMen"
            },
            {
                label: "Domestic Abuse from Upworthy",
                value: "DomesticAbuse"
            },
            {
                label: "School Experiment Artice from Upworthy",
                value: "SchoolExperiment"
            },
            {
                label: "Sad and Noble Government Artice from Upworthy",
                value: "SNGovernment"
            },
            {
                label: "Don Lemon Artice from Upworthy",
                value: "DonLemon"
            },
            {
                label: "Conspiracy Theorist Artice from Upworthy",
                value: "ConspiracyTheorist"
            },
            {
                label: "Ice Bucket Artice from Upworthy",
                value: "IceBucket"
            },
            {
                label: "Biology from Upworthy",
                value: "Biology"
            },
            {
                label: "Chemical Experiments with Animals from Upworthy",
                value: "ChemAnimals"
            }
        ]
    },
    {
        label: "ABC Articles",
        options: [
            {
                label: "Russia Ukraine from ABC",
                value: "RussiaUkraine"
            },
            {
                label: "Russian Oligarchs from ABC",
                value: "RussianOligarchs"
            },
            {
                label: "Abortion in Texas from ABC",
                value: "AbortionTexas"
            },
            {
                label: "Earthquake in Turkey from ABC",
                value: "EarthQuakeTurkey"
            },
            {
                label: "Amazon Union Vote from ABC",
                value: "AmazonUnion"
            },
        ]
    }
    
]

// The following values are directly from the outputs of the following models; we didn't have time to make APIs so we hard-coded the outputs below
// For validation, please ask any of our team members to run the models and show you from their respective laptops and GUIs
// autoGeneratedHeadline is based off the Facebook Bart CNN Model - slightly truncated to fit within a reasonable size
// sentiment analysis is found using Vader sentiment analysis
// similarity is found using Dandelion.eu 
const headlines = {
    "RapeArticle": {
        actualHeadline: "Ever Wonder How Much Rape Costs? Yep. There's Actually A Number.",
        autoGeneratedHeadline: "Sexualized and domestic violence costs the U.S. $5.8 billion.",
        scoreAct: -0.4939,
        scoreGen: -0.6249,
        similarity: "10%"
    },
    "SexismMen": {
        actualHeadline: "This Is What Sexism Against Men Sounds Like",
        autoGeneratedHeadline: "Boys face a number of pressures related to their gender.",
        scoreAct: 0.3612,
        scoreGen: -0.25,
        similarity: "56%"
    }, 
    "DomesticAbuse": {
        actualHeadline: "Listen To This 6 Year Old Call 9-1-1 When Her Stepdad Beats Her Mom",
        autoGeneratedHeadline: "This is an audio recording of a 911 call made by a 6-year-old girl who is witnessing her mother being beaten by her stepfather.",
        scoreAct: 0,
        scoreGen: -0.4215,
        similarity: "8%"
    },
    "SchoolExperiment": {
        actualHeadline: "A Bunch Of Schools In Oregon Tried An Experiment. And The Results? Just Wow.",
        autoGeneratedHeadline: "Programs like this involve kids in planting gardens, tending them, harvesting, and then cooking and eating the fruits (or veggies) of their labor.",
        scoreAct: 0.5859,
        scoreGen: 0.3612,
        similarity: "13%"
    }, 
    "SNGovernment": {
        actualHeadline: "Take Note... This Is Probably The Most Sad And Noble Thing Any Government Has Ever Done.",
        autoGeneratedHeadline: " The government has a plan for permanently evacuating every single person.",
        scoreAct: -0.0334,
        scoreGen: -0.6798,
        similarity: "29%"
    },
    "DonLemon": {
        actualHeadline: "The Question Don Lemon 'Had To Ask' This Rape Accuser That Made Him A Twitter Laughing Stock",
        autoGeneratedHeadline: "Oliver Willis started the #DonLemonReporting hashtag to point out just how idiotic it is to ask victims what they could've done differently.",
        scoreAct: -0.5307,
        scoreGen: -0.7096,
        similarity: "45%"
    }, 
    "ConspiracyTheorist": {
        actualHeadline: "I'm Not A Conspiracy Theorist But Learning About Movie Ratings Has Me Reaching For The Tin Foil",
        autoGeneratedHeadline: "The MPAA changes movies before we even see them to make sure they're decent.",
        scoreAct: 0.4745,
        scoreGen: 0.3182,
        similarity: "39%"
    }, 
    "IceBucket": {
        actualHeadline: "He Didn't Do The Ice Bucket Challenge, But He Did Something I Could Never Do",
        autoGeneratedHeadline: "Nick Triolo ran 70 miles in one day to protest an open-pit mine in Mexico",
        scoreAct: 0.0387,
        scoreGen: -0.25,
        similarity: "0%"
    }, 
    "Biology": {
        actualHeadline: "Something Happened 28 Years Ago And It's Making Spiderwebs, Birds, And 'Shrooms Go BERSERK",
        autoGeneratedHeadline: "An explosion and fire at the nuclear reactor in what was then the Soviet Union in Chernobyl Ukraine launched a plume of radioactive fallout.",
        scoreAct: 0,
        scoreGen: -0.2263,
        similarity: "24%"
    }, 
    "ChemAnimals": {
        actualHeadline: "The First 1 Minute And 20 Seconds Are So Hard To Watch, But The End Is Just Too Important",
        autoGeneratedHeadline: "For decades scientists have tried to understand the effects of chemical exposure by experimenting on animals.",
        scoreAct: 0.1942,
        scoreGen: 0,
        similarity: "0%"
    },
    "RussiaUkraine": {
        actualHeadline: "Russia-Ukraine live updates: Russia has lost 15-20% of combat power, US says",
        autoGeneratedHeadline: "Russian President Vladimir Putin's special military operation into neighboring Ukraine is losing combat power",
        scoreAct: -0.5719,
        scoreGen: -0.3182,
        similarity: "48%"
    },
    "RussianOligarchs": {
        actualHeadline: "With eyes on 'Londongrad,' UK seeks to overhaul ties to Russian oligarchs",
        autoGeneratedHeadline: "At least £1.5 billion worth of U.K. property is owned by Russians with links to the Kremlin. ",
        scoreAct: 0,
        scoreGen: 0.2263,
        similarity: "44%"
    },
    "AbortionTexas": {
        actualHeadline: "Woman faces Texas murder charge after self-induced abortion",
        autoGeneratedHeadline: "Lizelle Herrera, 26, is charged with murder in Texas. Authorities say she caused the death of an individual by self-induced abortion.",
        scoreAct: -0.6908,
        scoreGen: -0.886,
        similarity: "53%"
    },
    "EarthQuakeTurkey": {
        actualHeadline: "Powerful 5.2 magnitude earthquake hits eastern Turkey",
        autoGeneratedHeadline: "The 5.2 magnitude quake struck the town of Puturge in Malatya province.",
        scoreAct: 0.4215,
        scoreGen: -0.25,
        similarity: "75%"
    },
    "AmazonUnion": {
        actualHeadline: "Amazon seeks to overturn union win, says vote was tainted",
        autoGeneratedHeadline: "Amazon says union organizers and the National Labor Relations Board tainted the election.",
        scoreAct: 0.6705,
        scoreGen: 0.1779,
        similarity: "60%"
    },
}


const groupStyles = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
};
const groupBadgeStyles = {
    backgroundColor: '#EBECF0',
    borderRadius: '2em',
    color: '#172B4D',
    display: 'inline-block',
    fontSize: 12,
    fontWeight: 'normal',
    lineHeight: '1',
    minWidth: 1,
    padding: '0.16666666666667em 0.5em',
    textAlign: 'center',
};

const formatGroupLabel = (data) => (
    <div style={groupStyles}>
        <span>{data.label}</span>
        <span style={groupBadgeStyles}>{data.options.length}</span>
    </div>
);
export default function MainBody() {
    const [actHead, setActHead] = useState(headlines.RapeArticle.actualHeadline);
    const [autoHead, setAutoHead] = useState(headlines.RapeArticle.autoGeneratedHeadline);
    const [articleSelected, setArticleSelected] = useState(headlines.RapeArticle);
    const [anchorEl, setAnchorEl] = useState(null);
    const [whatsSelected, setWhatsSelected] = useState(0);

    function onChange(option) {
        setActHead(headlines[option.value].actualHeadline)
        setAutoHead(headlines[option.value].autoGeneratedHeadline)
        setArticleSelected(headlines[option.value]);
    }

    const handleClick = (event, whatsSelected) => {
        setAnchorEl(event.currentTarget);
        setWhatsSelected(whatsSelected);
    };

    
    const handleClose = () => {
        setAnchorEl(null);
    };

    return (
        <Wrapper>
            <Description>In this demo, we took articles from Upworthy which our model categorized as clickbait and ran Facebook's Bart CNN summarizer model on them to see if auto-generated headlines based on the articles' contents were less "click-baitey" than Upworthy's provided headlines.</Description>
            <div style={{width: "300px"}}>
                <Select formatGroupLabel={formatGroupLabel} defaultValue={options[0]} onChange={onChange} options={options}/>
            </div>
            <HeadlineComparisonContainer>
                <HeadlineContainer onClick={(e) => handleClick(e, 0)}>
                    <HeadlineTitle>Headline of Upworthy</HeadlineTitle>
                    {actHead}
                </HeadlineContainer>
                <HeadlineContainer onClick={(e) => handleClick(e, 1)}>
                    <HeadlineTitle>Bart Model Summarizer Headline</HeadlineTitle>
                    {autoHead}
                </HeadlineContainer>
                <Popover
                open={Boolean(anchorEl)}
                anchorEl={anchorEl}
                onClose={handleClose}
                anchorOrigin={{
                    vertical: 'center',
                    horizontal: 'center',
                }}
                transformOrigin={{
                    vertical: 'center',
                    horizontal: 'center',
                }}>
                    <Modal>
                        <ModalTitle>Metrics</ModalTitle>
                        <div style={{height: '225px', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
                            <SentimentBubble score={whatsSelected === 0 ? articleSelected.scoreAct: articleSelected.scoreGen}>
                                {whatsSelected === 0 ? Math.abs(articleSelected.scoreAct) : Math.abs(articleSelected.scoreGen)}
                            </SentimentBubble>
                        </div>
                        <ModalTitle style={{textAlign: 'center', fontWeight: "normal", marginTop: "5px", fontSize: "15px"}}>Vader sentiment analysis evaluation. Green is positive, red is negative, and magnitude is strength of emotion.</ModalTitle>
                    </Modal>
                </Popover>
            </HeadlineComparisonContainer>
            <SemanticSimilarity>Semantic similarity calculated using Dandelion.eu: <span style={{fontWeight: "bold", color: parseInt(articleSelected.similarity) <= 40 ? "#FA6262" : "#a5a58d"}}>{articleSelected.similarity}</span></SemanticSimilarity>
        </Wrapper>
    )
}
